export const TOGGLE_LOGIN_PANEL = 'TOGGLE_LOGIN_PANEL'
export const TOGGLE_REGISTER_PANEL = 'TOGGLE_REGISTER_PANEL'
export const TOGGLE_PASS_PANEL = 'TOGGLE_PASS_PANEL'
export const TOGGLE_MODIFY_PANEL = 'TOGGLE_MODIFY_PANEL'
export const TOGGLE_PHONE_PANEL = 'TOGGLE_PHONE_PANEL'
export const SET_USER_INFO = 'SET_USER_INFO'

// 首页数据
export const SET_BANNER = 'SET_BANNER'
export const SET_RECOMMEND_SUBJECT = 'SET_RECOMMEND_SUBJECT'
export const SET_HOT_READ_LIST = 'SET_HOT_READ_LIST'

// 书籍
export const SET_BOOK_LIST = 'SET_BOOK_LIST'
export const SET_BOOK_INFO = 'SET_BOOK_INFO'
export const STE_CATALOG = 'STE_CATALOG'
export const SET_RELATED_BOOK_LIST = 'SET_RELATED_BOOK_LIST'
export const SET_COMMENTS = 'SET_COMMENTS'

// 专题
export const SET_SUBJECT_RECOMMEND_LIST = 'SET_SUBJECT_RECOMMEND_LIST'
export const SET_SUBJECT_INFO = 'SET_SUBJECT_INFO'

// 知识点
export const SET_KNOWLEDGE_LIST = 'SET_KNOWLEDGE_LIST'
export const SET_KNOWLEDGE_INFO = 'SET_KNOWLEDGE_INFO'
export const SET_KNOWLEDGE_CHAPTER_LIST = 'SET_KNOWLEDGE_CHAPTER_LIST'

// 分类
export const SET_COUNTRIES = 'SET_COUNTRIES'
export const SET_CATEGORY_LIST = 'SET_CATEGORY_LIST'
export const SET_CATEGORY_BOOK_LIST = 'SET_CATEGORY_BOOK_LIST'

// 搜索
export const SET_SEARCH_RESULT = 'SET_SEARCH_RESULT'