export UserInfo from '../UserInfo'
export userCenter from './userCenter'
export bookClassify from './bookClassify'
export bookInfo from './bookInfo'
export bookComment from './bookComment'
export orderInfo from './orderInfo'
export search from './search'
export readRecord from './readRecord'
export evaluation from './evaluation'
export extra from './extra'
export * as dict from './dict'
export bookShelf from './bookShelf'