export * as dict from '../../sbck/dict'
export readerServices from '../../reader'
export userInfo from '../../UserInfo'
export * as home from './home'
export * as login from './login'
export * as accountSetting from './accountSetting'
export * as bookDetail from './bookDetail'
export * as evaluation from './evaluation'
export * as helpCenter from './helpCenter'
export * as myStudy from './myStudy'
export * as readHistory from './readHistory'
export * as safeSetting from './safeSetting'
export * as search from './search'
export * as typeNav from './typeNav'
export * as myVip from './myVip'
export * as memberInfo from './memberInfo'
