export const TOGGLE_EDIT_MODE = 'TOGGLE_EDIT_MODE'
// HOME
export const SET_BANNER = 'SET_BANNER'
export const SET_RECOMMEND_SUBJECT = 'SET_RECOMMEND_SUBJECT'
export const SET_HOT_READ_LIST = 'SET_HOT_READ_LIST'

// Subject
export const SET_SUBJECT_LIST = 'SET_SUBJECT_LIST'
export const SET_SUBJECT_DETAIL = 'SET_SUBJECT_DETAIL'

// Book
export const SET_BOOKINFO = 'SET_BOOKINFO'
export const SET_COMMENTS = 'SET_COMMENTS'
export const STE_CATALOG = 'STE_CATALOG'
export const SET_BOOKSHELF = 'SET_BOOKSHELF'
export const SET_BOOK_KNOWLEDGE_POINT = 'SET_BOOK_KNOWLEDGE_POINT'
export const SET_CATEGORY_BOOKLIST = 'SET_CATEGORY_BOOKLIST'
export const SET_CATEGORY_LIST = 'SET_CATEGORY_LIST'
export const SET_SUB_CATEGORY_LIST = 'SET_SUB_CATEGORY_LIST'
export const SET_HOT_BOOK_LIST = 'SET_HOT_BOOK_LIST'
export const SET_CHAPTER_LIST = 'SET_CHAPTER_LIST'
export const SET_RELATED_BOOK_LIST = 'SET_RELATED_BOOK_LIST'

// User
export const SET_USER_INFO = 'SET_USER_INFO'
export const SET_ORDER_LIST = 'SET_ORDER_LIST'
export const SET_HISTORY_LIST = 'SET_HISTORY_LIST'
export const SET_COMMENT_LIST = 'SET_COMMENT_LIST'
export const SET_ANNOTATION_LIST = 'SET_ANNOTATION_LIST'
export const SET_VIP_PRIVILEGE = 'SET_VIP_PRIVILEGE'
export const SET_VIP_LIST = 'SET_VIP_LIST'

// 分类
export const SET_COUNTRIES = 'SET_COUNTRIES'
export const SET_CATEGORY_BOOK_LIST = 'SET_CATEGORY_BOOK_LIST'

// Info
export const SET_QUOTE_LIST = 'SET_QUOTE_LIST'

// Search
export const SET_SEARCH_RESULT  = 'SET_SEARCH_RESULT'

// 知识点
export const SET_KNOWLEDGE_LIST = 'SET_KNOWLEDGE_LIST'
export const SET_KNOWLEDGE_INFO = 'SET_KNOWLEDGE_INFO'
export const SET_KNOWLEDGE_CHAPTER_LIST = 'SET_KNOWLEDGE_CHAPTER_LIST'
